//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzsekovanjeRondelic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slug
    {
        public int id { get; set; }
        public decimal lenght { get; set; }
        public decimal width { get; set; }
        public decimal radious { get; set; }
        public decimal space { get; set; }
        public decimal result { get; set; }
    }
}
